output_dir: logs
seed: 123456
trainer:
  max_epochs: 100
  strategy: ddp
  log_every_n_steps: 100
  check_val_every_n_epoch: 1
  precision: 16-mixed
  gradient_clip_val: 0.5

wandb: null

checkpoint:
  save_dir: checkpoints
  save_top_k: 1
  mode: max
